using System;

namespace XX
{
	public enum TEKIND
	{
		_DEFAULT = -20,
		APPEAR_FROM = 20,
		DISAPPEAR_POW_TO,
		DMG_BLINK = 500,
		EVADE_BLINK,
		DMG_BLINK_ENEMY,
		COLOR_BLINK,
		GAS_COLOR_BLINK,
		COLOR_BLINK_BUSH,
		FADEIN = 520,
		FADEOUT,
		FADEOUT_IN,
		COLOR_BLINK_ADD = 540,
		COLOR_BLINK_ADD_FADEOUT,
		DMG_BLINK_FADING = 560,
		COLOR_FADEOUT = 600,
		UI_DMG_DARKEN = 1000,
		ENLARGE_BOUNCY = 4001,
		ABSORB_BOUNCY,
		ENLARGE_TRANSFORM,
		INITCARRY_BOUNCE = 4020,
		__CANNOT_OVERRIDE = 100000,
		QUAKE_VIB,
		QUAKE_SINH,
		QUAKE_SINV,
		BOUNCE_ZOOM_IN,
		BOUNCE_ZOOM_IN2,
		BOUNCE_ZOOM_IN_FIX
	}
}
