using System;

namespace nel
{
	public enum MGKIND
	{
		NONE,
		WHITEARROW,
		FIREBALL,
		DROPBOMB,
		THUNDERBOLT,
		POWERBOMB,
		PR_PUNCH = 9000,
		PR_SHOTGUN,
		PR_SLIDING,
		PR_WHEEL,
		PR_COMET,
		PR_SHIELD_BUSH,
		PR_SHIELD_LARIAT,
		PR_DASHPUNCH,
		PR_SHIELD_COUNTER,
		PR_SMASH,
		PR_BURST = 9500,
		TACKLE = 11000,
		GROUND_SHOCKWAVE = 11020,
		GENERAL_BEAM = 11030,
		NATTR_SPLASH_FIRE = 11950,
		NATTR_SPLASH_ICE,
		NATTR_SPLASH_THUNDER,
		BASIC_SHOT = 12000,
		CANDLE_SHOT = 14001,
		ICE_SHOT,
		CEILDROP,
		WEB_SHOT = 14010,
		THUNDERBALL_SHOT,
		ITEMBOMB_NORMAL = 50000,
		ITEMBOMB_LIGHT = 50010,
		ITEMBOMB_MAGIC = 50020,
		EF_WORM_PUBLISH = 200000,
		EF_WHOLEMAP
	}
}
